baseURL = "/"
languageCode = "fr-fr"
theme = "Hargo"
title = "Le blog du Marketer"
[[menu.main]]
name = "Accueil"
url = "https://stupefied-rosalind-bc906f.netlify.app/"
weight = 1

[params]
  mainSections = ["Accueil"]