baseURL = "/"
disqusShortname = ""
languageCode = "fr-fr"
paginate = 10
summaryLength = "20"
theme = "Hargo"
title = "Le blog du Marketer"
url = "https://stupefied-rosalind-bc906f.netlify.app/"
[[menu.main]]
URL = "contact"
name = "Nous contacter"
weight = 5
[[menu.main]]
URL = "blog"
name = "Articles"
weight = 3
[[menu.main]]
URL = "products"
name = "Abonnements"
weight = 4
[params]
author = "Themefisher"
copyright = "Copyright &copy; 2020 FGL SERVICES"
description = "This is meta description"
email = "demo@email.com"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
googleAnalitycsID = ""
home = "Accueil"
location = "Dhaka, Bangladedsh"
logo = "images/logo.png"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
mobile = "0124857985320"
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
[params.contact]
formAction = "#"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.rating]
enable = true
publicKey = "811cf0927332bf51f2e12f84608594ac"
websiteID = "444334"

