baseURL = "/"
disqusShortname = ""
languageCode = "fr-fr"
paginate = 10
summaryLength = "20"
theme = "Hargo"
title = "Le blog du Marketer"
url = "https://leblogdumarketer.netlify.app/"
[[menu.footer]]
name = "Site partenaire de PUCEBIOS.FR"
url = "https://www.pucebios.fr/"
weight = 2
[[menu.footer]]
name = "Contact"
weight = 1
[[menu.main]]
URL = "products"
name = "Abonnements"
weight = 2
[[menu.main]]
URL = "blog"
name = "Articles"
weight = 1
[[menu.main]]
URL = "contact"
name = "Nous contacter"
weight = 3
[params]
author = "Themefisher"
copyright = "Copyright &copy; 2020 FGL SERVICES"
description = "Le blog du Marketing par des experts"
email = "fglservices@gmail.com"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCGRcXg7i4_IdFzO_IESqttRni5d1T3vwQ&libraries=places"
googleAnalitycsID = ""
home = "Accueil"
location = "Rouen, France"
logo = "images/logo.png"
mapLatitude = "49.4404591"
mapLongitude = "1.0939658"
mapMarker = "images/marker.png"
mobile = "0612345678"
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
[params.contact]
formAction = "fglservices@gmail.com"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.rating]
enable = true
publicKey = "811cf0927332bf51f2e12f84608594ac"
websiteID = "444334"
[taxonomies]
Telechargements = "Telechargements"
difficulte = "difficulte"
